package calcul;


/**
* calcul/_calcul_montantsStub.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from calcul.idl
* lundi 7 janvier 2019 12 h 07 GMT
*/

public class _calcul_montantsStub extends org.omg.CORBA.portable.ObjectImpl implements calcul.calcul_montants
{
  // Constructors
  // NOTE:  If the default constructor is used, the
  //        object is useless until _set_delegate (...)
  //        is called.
  public _calcul_montantsStub ()
  {
    super ();
  }

  public _calcul_montantsStub (org.omg.CORBA.portable.Delegate delegate)
  {
    super ();
    _set_delegate (delegate);
  }

  public double calcul_ttc (double mt_ht, double taux)
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("calcul_ttc", true);
       _out.write_double (mt_ht);
       _out.write_double (taux);
       _in = _invoke (_out);
       double __result = _in.read_double ();
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return calcul_ttc (mt_ht, taux);
    } finally {
        _releaseReply (_in);
    }
  } // calcul_ttc

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calcul/calcul_montants:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s)
  {
     try 
     {
       String str = s.readUTF ();
       org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init ().string_to_object (str);
       org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
       _set_delegate (delegate);
     } catch (java.io.IOException e) {}
  }

  private void writeObject (java.io.ObjectOutputStream s)
  {
     try 
     {
       String str = org.omg.CORBA.ORB.init ().object_to_string (this);
       s.writeUTF (str);
     } catch (java.io.IOException e) {}
  }
} // class _calcul_montantsStub
