package calcul;


/**
* calcul/calcul_montants.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from calcul.idl
* lundi 7 janvier 2019 12 h 07 GMT
*/

public interface calcul_montants extends calcul_montantsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calcul_montants
