package calcul;


/**
* calcul/calcul_montants_Tie.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from calcul.idl
* lundi 7 janvier 2019 02 h 42 GMT
*/

public class calcul_montants_Tie extends org.omg.CORBA.portable.ObjectImpl
                implements calcul.calcul_montants, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public calcul_montants_Tie ()
  {
  }

  public calcul_montants_Tie (calcul.calcul_montantsOperations impl)
  {
    super ();
    _impl = impl;
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("calcul_ttc", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get (method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calcul/calcul_montants/calcul_ttc
       {
         double mt_ht = in.read_double ();
         double taux = in.read_double ();
         double __result = (double)0;
         __result = this.calcul_ttc (mt_ht, taux);
         out = rh.createReply();
         out.write_double (__result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  public double calcul_ttc (double mt_ht, double taux)
  {
    return _impl.calcul_ttc(mt_ht, taux);
  } // calcul_ttc

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calcul/calcul_montants:1.0"};

  public String[] _ids ()
  {
    return __ids;
  }

  private calcul.calcul_montantsOperations _impl;

} // class calcul_montants_Tie
