package calcul;


/**
* calcul/calcul_montantsOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from calcul.idl
* lundi 7 janvier 2019 12 h 07 GMT
*/

public interface calcul_montantsOperations 
{
  double calcul_ttc (double mt_ht, double taux);
} // interface calcul_montantsOperations
